### ISSUE TITLE
Error when unpacking a single BMU file

### ISSUE THREAD

**Issue by yanir99** [VladTheJunior/UnmergeTool#2]
I unpacked the S19 merged BMU file successfully, but when trying to unpack one of the single BMU's that were extracted, I'm getting this error:

`Detected single BMU file...

Header:

magic: 26
Traceback (most recent call last):
  File "bmu.py", line 275, in <module>
    main()
  File "bmu.py", line 267, in main
    unpack(args.file)
  File "bmu.py", line 250, in unpack
    unpack_single(file)
  File "bmu.py", line 67, in unpack_single
    file_count = int.bit_count(content)
AttributeError: type object 'int' has no attribute 'bit_count'`

**Comment by VladTheJunior** [comment]
What is your Python version?

According to docs https://docs.python.org/3/library/stdtypes.html#int.bit_count bit_count was added in 3.10

**Comment by yanir99** [comment]
Thanks for the tip 😊
Updated to 3.11 and all works now.


From: VladTheJunior ***@***.***>
Date: Saturday, 29. June 2024 at 02:48
To: VladTheJunior/BitmainFirmwareUnpacker ***@***.***>
Cc: Yanir Ben Nun ***@***.***>, Author ***@***.***>
Subject: Re: [VladTheJunior/BitmainFirmwareUnpacker] Error when unpacking a single BMU file (Issue #2)

What is your Python version?

According to docs https://docs.python.org/3/library/stdtypes.html#int.bit_count bit_count was added in 3.10
